### ISSUE TITLE
Autenticação com vue-authenticate?

### ISSUE THREAD

**Issue by alextpedro** [LoyalPotato/virt-wallet-dad#4]
Ainda não percebi muito bem como é que estamos a fazer a autenticação, mas estive a ver este package (https://www.npmjs.com/package/vue-authenticate) e parece-me uma maneira fácil de autenticar quase diretamente com o Vue.

**Comment by LoyalPotato** [comment]
A autenticação é feita através do laravel passport. 
Quando é feito um login, se o utilizador tiver credenciais válidas, será enviado um token para depois ser usado para acesso a outras partes da plataforma.
